appname: appName

environments:
- branch: release      
  namespace: dev

build:                          
  script: build.sh
  image: node:16-alpine  
          
dockerfiles:                             
- name: appName-api
  dockerfile: 'pipelines/Dockerfile.api'
  context: .
- name: appName-web
  dockerfile: 'pipelines/Dockerfile.standalone.web'
  context: .

####
# NOTES:
# i nuovi enviroment verranno aggiunti quando verrà fatto aggiunto l'env di produzione
# Se volete cambiare il nome dei dockerfile dovete aggiungere il parametro "deployment" 
#         com'è stato fatto per tomshow-api
# per gestire le configurazioni per stage e production c'è u commento nello script di build
###
