FROM node:16-alpine as base
RUN mkdir /opt/appName && chown -R node:node /opt/appName
WORKDIR /opt/appName
COPY . .

FROM base as web
ENV NODE_ENV=development
ENV ENV=development
RUN yarn
CMD ["yarn", "web:dev"]

FROM base as api
ENV NODE_ENV=development
ENV ENV=development
RUN yarn
CMD ["yarn", "api:dev"]
